# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty

# Pages
include:
  - _pages

# Setup
title: 'STEM Discovery Day'
tagline: 'STEM Discovery Day'
description: 'Science, Technology, Engineering and Math can be fun (and relevant)!'
url: http://stemday.ucls.uchicago.edu
urlbase: /STEM-Club-Website
baseurl: /STEM-Club-Website/
slash: /

author:
  name: 'The STEM Club Team'
  url: http://stemday.ucls.uchicago.edu
  
paginate: 5
paginate_path: "/updates/page:num/"

repository: agajews/STEM-Club-Website
